[package]
name = "helmoci-storage"
version.workspace = true
edition.workspace = true

[dependencies]
helmoci-core.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
moka.workspace = true
object_store.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
tempfile.workspace = true
